### ISSUE TITLE
How to set batch_size=128 of binarized-MNIST ?

### ISSUE THREAD

**Issue by XJWang0** [airalcorn2/deformer#1]
I set train, valid and test dataloader batch size = 128, but it went wrong. Can u tell me how to set it ? Thank u!

**Comment by airalcorn2** [comment]
[I disabled setting the `batch_size` for MNIST](https://github.com/airalcorn2/deformer#running-the-binarized-mnist-training-script) because I was only training on a single GPU and I would run out of memory at larger batch sizes. If you want to try training with larger batch sizes, you will need to refactor [`get_preds_labels`](https://github.com/airalcorn2/deformer/blob/3304a71e64217c8076f8986a0ac4e8347f7bb127/train_deformer.py#L76) in [`train_deformer.py`](https://github.com/airalcorn2/deformer/blob/master/train_deformer.py) and [`forward`](https://github.com/airalcorn2/deformer/blob/3304a71e64217c8076f8986a0ac4e8347f7bb127/deformer.py#L66) in [`deformer.py`](https://github.com/airalcorn2/deformer/blob/master/deformer.py#L66) to reshape the tensors, but it should be straightforward to do.

**Comment by XJWang0** [comment]
Thanks for your help!
